Notaneitor_v4.0Web/src/com/sdi/presentation/AsignaturasBean.java
package com.sdi.presentation;

import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import com.sdi.business.services.AsignaturasService;
import com.sdi.infrastructure.Factories;
import com.sdi.model.Asignatura;
import com.sdi.model.Matricula;
import com.sdi.model.Usuario;

@ManagedBean(name = "asignaturas")
@SessionScoped
public class AsignaturasBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6818771884269267983L;

	private Asignatura asigantura;
	private Matricula matricula;
	String nota;

	public Matricula getMatricula() {
		return matricula;
	}
	
	

	public String getNota() {
		return nota;
	}



	public void setNota(String nota) {
		this.nota = nota;
	}



	public void setMatricula(Matricula matricula) {
		this.matricula = matricula;
		this.nota = matricula.getNota();
	}

	private List<Usuario> usuariosNoCursanAsignatura = null;

	public List<Usuario> getUsuariosNoCursanAsignatura() {
		return usuariosNoCursanAsignatura;
	}

	public void setUsuariosNoCursanAsignatura(Asignatura a) {
		this.asigantura = a;
		this.usuariosNoCursanAsignatura = Factories.services
				.createAsignaturasService()
				.obtenerAlumnosQueNoCursanAsignatura(a);
	}


	public List<Asignatura> getAsignaturas() {
		return Factories.services.createAsignaturasService().getAsignaturas();
	}

	public Asignatura getAsigantura() {
		return asigantura;
	}

	public void setAsigantura(Asignatura asigantura) {
		this.asigantura = asigantura;
	}

	public void save() {
		AsignaturasService as = Factories.services.createAsignaturasService();

		if (asigantura.getId() == null) { // nueva asignatura
			as.addNewCourse(this.asigantura);
		} else {
			as.updateCourse(this.asigantura);
		}
	}

	public void delete(Asignatura asig) {
		Factories.services.createAsignaturasService().deleteCourse(asig);
	}

	public void iniciaAsignatura() {
		asigantura = new Asignatura();
	}

	public String matricularAlumno(Usuario u){
		Factories.services.createAlumnoService().matricular(u,this.asigantura);
		this.setUsuariosNoCursanAsignatura(this.asigantura);
		return "/restricted/matriculaAlumno";
	}
	
	public List<Matricula> getMatriculaPorAsignatura(){
		return Factories.services.createAsignaturasService().getMatriculasAsignatura(this.asigantura);
	}
	
	public void calificar(Matricula m){
		System.out.println(m.getAlumno());
		System.out.println(asigantura);
		System.out.println(m.getNota());
		AsignaturasService as = Factories.services.createAsignaturasService();
		as.calificarAlumno(m.getAlumno(), asigantura, m.getNota());
		
	}
}

Notaneitor_v4.0Web/src/com/sdi/presentation/ProfesoresBean.java
package com.sdi.presentation;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import com.sdi.business.services.AsignaturasService;
import com.sdi.infrastructure.Factories;
import com.sdi.model.Asignatura;
import com.sdi.model.Profesor;
import com.sdi.model.Usuario;

@ManagedBean(name = "profesores")
@SessionScoped
public class ProfesoresBean implements Serializable {

	private static final long serialVersionUID = -9133607118906114386L;
	private Profesor profesor;
	private List<Asignatura> asignaturasQueNoImparte;

	/**
	 * Obtiene todos los profesores de la base de datos
	 * 
	 * @return
	 */
	public List<Profesor> getProfesores() {
		return Factories.services.createUsuariosService().getProfesores();
	}

	public void setUsuario(Usuario profesor) {

		this.profesor = getProfesorByID(profesor);
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	private void setAsignaturasNoImparteProfesor() {
		AsignaturasService as = Factories.services.createAsignaturasService();
		List<Asignatura> todas = as.getAsignaturas();
		List<Asignatura> asignaturasQueNoImparte = new ArrayList<Asignatura>();
		
		if(profesor.getAsignaturas() == null){
			this.asignaturasQueNoImparte = todas;
			return;
		}

		for (Asignatura asignatura : todas) {
			if (!contiene(asignatura, profesor.getAsignaturas())) {
				asignaturasQueNoImparte.add(asignatura);
			}
		}
		this.asignaturasQueNoImparte = asignaturasQueNoImparte;
	}

	public List<Asignatura> getAsignaturasQueNoImparte() {
		setAsignaturasNoImparteProfesor();
		return asignaturasQueNoImparte;
	}

	private boolean contiene(Asignatura asignatura, List<Asignatura> asignaturas) {
		for (Asignatura m : asignaturas) {
			if (m.getNombre().equals(asignatura.getNombre())) {
				return true;
			}
		}
		return false;
	}

	private Profesor getProfesorByID(Usuario profesor) {
		for (Profesor p : Factories.services.createUsuariosService()
				.getProfesores()) {
			if (p.getLogin().equals(profesor.getLogin())) {
				return p;
			}
		}
		return null;
	}

	
	public List<Asignatura> getMisAsignaturas(){
		Usuario u = (Usuario)Session.get("LOGGEDIN_USER");
		List<Profesor> profesores = Factories.services.createUsuariosService().getProfesores();
		for(Profesor p : profesores){
			if(p.getLogin().equals(u.getLogin())){
				return p.getAsignaturas();
			}
		}
		return null;
	}

}

Notaneitor_v4.0Web/WebContent/restricted/altaAsignatura.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template-general.xhtml">
	<ui:define name="titulo">
    #{msgs.tituloOperacionAlta}
</ui:define>

	<ui:define name="cuerpo">
		<h:form id="form-principal">
			<ui:include src="/snippets/form-asignatura.xhtml" />
		</h:form>
	</ui:define>

</ui:composition>

Notaneitor_v4.0Web/WebContent/restricted/asignarProfesor.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template-general.xhtml">
	<ui:define name="titulo">
    #{msgs.tituloOperacionEdicion}
</ui:define>

	<ui:define name="top">
		<ui:include src="/templates/template-general.xhtml" />
	</ui:define>

	<ui:define name="cuerpo">
		<h:form id="form-principal">
			<fieldset>
				<legend>#{msgs.LEGEND_ASIGNAR_PROFESORES}
					#{imparte.asignatura.nombre}</legend>
				<h:dataTable value="#{imparte.profesoresQueNoImpartenAsignatura}"
					var="prf" class="table table-bordered"
					rendered="#{imparte.profesoresQueNoImpartenAsignatura.size() != 0}">
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_NOMBRE_USUARIO}</f:facet>
						#{prf.name}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_APELLIDOS_USUARIO}</f:facet>
						#{prf.apellidos}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_EMAIL_USUARIO}</f:facet>
						#{prf.email}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.OPCIONES}</f:facet>
						<h:commandButton id="asignar"
							value="#{msgs.ASIGN_TO} #{imparte.asignatura.nombre}"
							actionListener="#{imparte.asignarAsignatura(prf)}"
							immediate="true" />
					</h:column>
				</h:dataTable>
				
				
					<h:outputText
					value="#{msgs.TEACHERS_NOT_AVAIBLE}"
					rendered="#{imparte.profesoresQueNoImpartenAsignatura.size() == 0}" />				
				
				

			</fieldset>
		</h:form>
	</ui:define>


</ui:composition>

Notaneitor_v4.0Web/WebContent/restricted/calificar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template-general.xhtml">
	<ui:define name="titulo">
    #{msgs.tituloOperacionEdicion}
</ui:define>

	<ui:define name="cuerpo">
		<h:form id="form-principal">
			<fieldset>
				<legend>#{asignaturas.asigantura.nombre}</legend>
				<h:dataTable value="#{asignaturas.matriculaPorAsignatura}"
					var="matr" class="table table-bordered">
					<h:column>
						<f:facet name="header">Nombre</f:facet>
						#{matr.alumno.nombre}
					</h:column>

					<h:column>
						<f:facet name="header">Apellidos</f:facet>
						#{matr.alumno.apellidos}
					</h:column>

					<h:column>
						<f:facet name="header">Email</f:facet>
						#{matr.alumno.email}
					</h:column>

					<h:column>
						<f:facet name="header">Asignatura</f:facet>
						#{matr.asignatura}
					</h:column>
					
					<h:column>
						<f:facet name="header">Antigua nota</f:facet>
						#{matr.nota}
					</h:column>

					<h:column>
						<f:facet name="header">Nota</f:facet>
						<h:inputText id="nota" value="#{asignaturas.nota}">
							<f:validator validatorId="com.sdi.presentation.validator.ValidadorNota"/>
						</h:inputText>
						<h:message for="nota"/>
						<h:commandButton value="Calificar"
							action="#{asignaturas.calificar(matr)}"
							actionListener="#{matr.setNota(asignaturas.nota)}"
							>
							
						</h:commandButton>
					</h:column>
				</h:dataTable>
			</fieldset>



		</h:form>
	</ui:define>

</ui:composition>

Notaneitor_v4.0Web/WebContent/restricted/editForm.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template-general.xhtml">
	<ui:define name="titulo">
    #{msgs.tituloOperacionEdicion}
</ui:define>

	<ui:define name="cuerpo">
		<h:form id="form-principal" >
			<ui:include src="/snippets/form-usuario.xhtml" />
		</h:form>
	</ui:define>

</ui:composition>

Notaneitor_v4.0Web/WebContent/restricted/matriculaAlumno.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template-general.xhtml">
	<ui:define name="titulo">
    #{msgs.tituloOperacionEdicion}
</ui:define>

	<ui:define name="top">
		<ui:include src="/templates/template-general.xhtml" />
	</ui:define>

	<ui:define name="cuerpo">
		<h:form id="form-principal">
			<fieldset>
				<legend>#{asignaturas.asigantura.nombre}</legend>
				<h:dataTable value="#{asignaturas.usuariosNoCursanAsignatura}"
					var="prf" id="tabla" class="table table-bordered" border="1" rendered="#{asignaturas.usuariosNoCursanAsignatura.size() != 0}">
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_NOMBRE_USUARIO}</f:facet>
						#{prf.name}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_APELLIDOS_USUARIO}</f:facet>
						#{prf.apellidos}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_EMAIL_USUARIO}</f:facet>
						#{prf.email}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.MATRICULAR}</f:facet>
						<h:commandButton id="matricular" value="#{msgs.MATRICULAR}"
							action="#{asignaturas.matricularAlumno(prf)}"
							actionListener="#{asignaturas.setUsuariosNoCursanAsignatura(asignaturas.asigantura)}"
							>
							<f:ajax render="@form :form-principal" execute="@form" />
						</h:commandButton>
					</h:column>
					<h:message for="tabla"/>
				</h:dataTable>
				<h:outputText value="#{msgs.NOT_AVAIBLE_STUDENTS}" rendered="#{asignaturas.usuariosNoCursanAsignatura.size() == 0}"/>
				
			</fieldset>
		</h:form>
	</ui:define>

</ui:composition>

Notaneitor_v4.0Web/WebContent/restricted/opciones.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template-general.xhtml">
	<ui:define name="titulo">
    #{msgs.tituloOpciones}
</ui:define>

	<ui:define name="cuerpo">

		<h:form id="form-principal">

			<h:body rendered="#{LOGGEDIN_USER.rol == 'admin'}">
				<fieldset>
					<legend>#{msgs.TITULO_OPCIONES_ADMIN_USUARIOS}</legend>
					<h:dataTable value="#{usuarios.usuarios}" var="users" border="1"
						class="table table-bordered">
						<h:column>
							<f:facet name="header">#{msgs.ID}</f:facet>
							#{users.id}
					</h:column>
						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_NOMBRE_USUARIO}</f:facet>
							#{users.name}
						</h:column>
						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_APELLIDOS_USUARIO}</f:facet>
							#{users.apellidos}
						</h:column>
						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_EMAIL_USUARIO}</f:facet>
							#{users.email}
						</h:column>
						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_LOGIN_USUARIO}</f:facet>
							#{users.login}
						</h:column>
						<h:column>
							<f:facet name="header">#{msgs.ACTIVAR}</f:facet>
							<h:commandLink class="btn btn-block btn-lg btn-success"
								action="#{usuarios.cambiarEstadoActivacion(users)}"
								type="submit" value="#{msgs.ACTIVAR_MENSAJE}" immediate="true"
								rendered="#{users.activada == false}">
								<f:ajax execute="@this" render="@form" />
							</h:commandLink>

							<h:commandLink class="btn btn-block btn-lg btn-danger"
								action="#{usuarios.cambiarEstadoActivacion(users)}"
								type="submit" value="#{msgs.DESACTIVAR_MENSAJE}"
								immediate="true" rendered="#{users.activada == true}">
								<f:ajax execute="@this" render="@form" />
							</h:commandLink>
						</h:column>


						<h:column rendered="false">
							<f:facet name="header">Baja</f:facet>
							<h:commandLink action="#{usuarios.baja(users)}"
								class="btn btn-block btn-lg btn-danger" type="submit"
								value="Baja" immediate="true">

								<f:ajax execute="@this" render="@form" />
							</h:commandLink>
						</h:column>


						<h:column>
							<f:facet name="header">#{msgs.EDITAR}</f:facet>
							<h:commandLink action="#{instant.editRequest}" type="submit"
								value="#{msgs.EDITAR_MENSAJE}"
								class="btn btn-block btn-lg btn-info"
								actionListener="#{usuarios.setUser(users)}" immediate="true">
							</h:commandLink>
						</h:column>

						<h:column>
							<f:facet name="header">#{msgs.OPCIONES}</f:facet>
							<h:commandLink action="#{instant.asignarAsignaturasRequesr}" type="submit"
								value="#{msgs.ASIGNAR_ASIGNATURAS}"
								actionListener="#{profesores.setUsuario(users)}"
								class="btn btn-block btn-lg btn-info" immediate="true"
								rendered="#{users.rol == 'profesor'}">
							</h:commandLink>

							<h:commandLink action="#{instant.asignarAsignaturasAlumnoRequest}" type="submit"
								value="#{msgs.MATRICULAR_ASIGNATURAS}"
								class="btn btn-block btn-lg btn-info"
								actionListener="#{matricula.setAlumno(users)}" immediate="true"
								rendered="#{users.rol == 'alumno'}">
							</h:commandLink>
						</h:column>
					</h:dataTable>
				</fieldset>


				<h:commandLink action="#{instant.altaAsignaturaRequest}" type="submit"
					value="#{msgs.ANADIR_ASIGNATURA}" immediate="true"
					class="btn btn-block btn-lg btn-info"
					actionListener="#{asignaturas.iniciaAsignatura}" />
				<fieldset>
					<legend>#{msgs.TITULO_LEGEND_OPCIONES_ASIGNATURAS_ADMIN}</legend>
					<h:dataTable value="#{asignaturas.asignaturas}" var="asig"
						border="1" class="table table-bordered">
						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_CODIGO_ASIGNATURA}</f:facet>
								#{asig.codigo}
							</h:column>

						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_NOMBRE_ASIGNATURA}</f:facet>
								#{asig.nombre}
							</h:column>

						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_CURSO_ASIGNATURA}</f:facet>
								#{asig.curso}
							</h:column>

						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_CREDITOS_ASIGNATURA}</f:facet>
								#{asig.creditos}
							</h:column>

						<h:column>
							<f:facet name="header">#{msgs.BAJA}</f:facet>
							<h:commandLink action="#{asignaturas.delete(asig)}" type="submit"
								class="btn btn-block btn-lg btn-danger"
								value="#{msgs.BAJA_MENSAJE}" immediate="true"
								rendered="#{asig.deletable}">
								<f:ajax execute="@this" render="@form" />
							</h:commandLink>
						</h:column>

						<h:column>
							<f:facet name="header">#{msgs.EDITAR}</f:facet>
							<h:commandLink action="#{instant.editarAsignaturaRequest}" type="submit"
								value="#{msgs.EDITAR}"
								class="btn btn-block btn-lg btn-info"
								actionListener="#{asignaturas.setAsigantura(asig)}"
								immediate="true">
							</h:commandLink>
						</h:column>

						<h:column>
							<div class="btn-group">
								<ul>
									<li><h:commandLink action="#{instant.asignarAlumnosAsignaturaRequest}" type="submit"
											class="btn btn-block btn-lg btn-info"
											value="#{msgs.ASIGNAR_ALUMNOS_ASIGNATURA}"
											actionListener="#{asignaturas.setUsuariosNoCursanAsignatura(asig)}"
											immediate="true">
										</h:commandLink> <br /></li>


									<li><h:commandLink action="#{instant.asignarProfesoresAsignaturaRequest}" type="submit"
											class="btn btn-block btn-lg btn-info"
											value="#{msgs.ASIGNAR_PROFESORES_ASIGNATURA}"
											actionListener="#{imparte.setAsignatura(asig)}"
											immediate="true">
										</h:commandLink></li>

								</ul>
							</div>
						</h:column>

					</h:dataTable>
				</fieldset>
			</h:body>

			<h:body rendered="#{LOGGEDIN_USER.rol == 'alumno'}">
				<fieldset>
					<legend>#{msgs.TITULO_LEGEND_OPCIONES_ALUMNO}
						#{LOGGEDIN_USER.name} #{LOGGEDIN_USER.apellidos}</legend>
					<h:dataTable value="#{controller.matricula}" var="o" border="1"
						class="table table-bordered">

						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_NOMBRE_ASIGNATURA}</f:facet>
    						#{o.asignatura}
    					</h:column>

						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_NOTA}</f:facet>
    						#{o.nota}
    					</h:column>
					</h:dataTable>
				</fieldset>

			</h:body>

			<h:body rendered="#{LOGGEDIN_USER.rol == 'profesor'}">
				<fieldset>
					<legend>#{msgs.TITULO_OPCIONES_PROFESOR}</legend>
					<h:dataTable value="#{profesores.misAsignaturas}" var="asig"
						class="table table-bordered">
						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_NOMBRE_ASIGNATURA}</f:facet>
							#{asig.nombre}
						</h:column>

						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_CODIGO_ASIGNATURA}</f:facet>
							#{asig.codigo}
						</h:column>

						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_CURSO_ASIGNATURA}</f:facet>
							#{asig.curso}
						</h:column>

						<h:column>
							<f:facet name="header">#{msgs.TITULO_CELDA_CREDITOS_ASIGNATURA}</f:facet>
							#{asig.creditos}
						</h:column>

						<h:column>
							<f:facet name="header">#{msgs.OPCIONES}</f:facet>
							<h:commandLink value="#{msgs.OPCIONES_PROFESOR_CALIFICAR}"
								action="#{instant.calificarRequest}"
								actionListener="#{asignaturas.setAsigantura(asig)}" />
						</h:column>
					</h:dataTable>
				</fieldset>

			</h:body>

		</h:form>

	</ui:define>


</ui:composition>

Notaneitor_v4.0Web/WebContent/restricted/perfilAsignaturasAlumno.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template-general.xhtml">
	<ui:define name="titulo">
    #{msgs.tituloOperacionEdicion}
</ui:define>
	<ui:define name="top">
		<ui:include src="/templates/template-general.xhtml" />
	</ui:define>
	<ui:define name="cuerpo">
		<h:form id="form-principal">
			<fieldset>
				<legend>#{msgs.LEGEND_PERFIL_ASIGNATURAS_ALUMNO} #{matricula.alumno.name} #{matricula.alumno.apellidos} </legend>
				<h:dataTable var="asig"
					value="#{matricula.asignaturasNoMatriculadas}" border="1"
					class="table table-bordered"
					rendered="#{matricula.asignaturasNoMatriculadas.size() != 0}">
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_NOMBRE_ASIGNATURA}</f:facet>
						#{asig.nombre}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.MATRICULAR}</f:facet>
						<h:commandButton id="matricular" value="#{msgs.MATRICULAR_BOTON}"
							action="#{matricula.matricula(asig)}"
							class="btn btn-block btn-lg btn-success"
							>
							<f:ajax render="@form :form-principal" execute="@form" />
						</h:commandButton>
					</h:column>
				</h:dataTable>
				<h:outputText
					value="#{msgs.NOT_COURSES_AVAIBLE}"
					rendered="#{matricula.asignaturasNoMatriculadas.size() == 0}" />
			</fieldset>
			<fieldset>
				<legend>
					#{msgs.MY_COURSES}
				</legend>
				
				<h:dataTable value="#{matricula.asignaturasMatriculadas}" var="as" class="table table-bordered" rendered="#{matricula.asignaturasMatriculadas.size() != 0}">
				
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_CODIGO_ASIGNATURA}</f:facet>
						#{as.asignatura}
					</h:column>
					
					<h:column>
						<f:facet name="header"> #{msgs.BAJA_MENSAJE} </f:facet>
						<h:commandButton
							value=" #{msgs.BAJA_MENSAJE}"
							action="#{instant.alumnoBajaAsignaturaRequest}"
							actionListener="#{matricula.baja(as)}"
							rendered="#{as.nota == 'No calificado'}"
							class="btn btn-block btn-lg btn-danger"
						/>
					</h:column>
				
				</h:dataTable>
				
				<h:outputText value = "#{msgs.NOT_COURSES_AVAIBLE}" rendered="#{matricula.asignaturasMatriculadas.size() == 0}"/>
			
			</fieldset>
	
		</h:form>
	</ui:define>

</ui:composition>

Notaneitor_v4.0Web/WebContent/restricted/perfilAsignaturasProfesor.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template-general.xhtml">
	<ui:define name="titulo">
    #{msgs.tituloOperacionEdicion}
</ui:define>

	<ui:define name="top">
		<ui:include src="/templates/template-general.xhtml" />
	</ui:define>

	<ui:define name="cuerpo">
		<h:form id="form-principal">

			<fieldset>
				<legend> #{msgs.LEGEND_PERFIL_ASIGNATURAS_PROFESOR} #{profesores.profesor.name} </legend>
				<h:dataTable value="#{profesores.asignaturasQueNoImparte}"
					var="asig" class="table table-bordered">
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_NOMBRE_ASIGNATURA}</f:facet>
						#{asig.nombre}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_CODIGO_ASIGNATURA}</f:facet>
						#{asig.codigo}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_CREDITOS_ASIGNATURA}</f:facet>
						#{asig.creditos}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.TITULO_CELDA_CURSO_ASIGNATURA}</f:facet>
						#{asig.curso}
					</h:column>
					<h:column>
						<f:facet name="header">#{msgs.CELDA_OPCIONES}</f:facet>
						<h:commandButton id="asignar"
							value="#{msgs.ASIGN_TO} #{profesores.profesor.name}"
							action="#{imparte.asignarAsignatura(asig)}"
							actionListener="#{imparte.setProfesor(profesores.profesor)}">
						</h:commandButton>
					</h:column>
				</h:dataTable>
			</fieldset>
		</h:form>
	</ui:define>

</ui:composition>